[package]
name = "asset_migrator"
version = "1.0.0"
edition = "2021"

license = "BSD-3"

authors = [
    "Liam R. (zCubed3) <zcubedtres@gmail.com>",
    "notnotnotswipez"
]

[dependencies]
rayon = "1.8.0"
